[workspace]
members = [
]
[package]
name = "z80"
authors = ["kirjavasciprt"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "z80"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
c2rust-bitfields= "0.3"
