[workspace]
members = [
]
[package]
name = "z80"
authors = ["kirjavasciprt"]
version = "0.0.0"
edition = "2021"

[lib]
name = "z80"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
c2rust-bitfields= "0.3"

[profile.test]
opt-level = 3
