[workspace]
members = [
]
[package]
name = "z80"
authors = ["Kirjava"]
version = "0.0.1"
edition = "2021"
license = "MIT"

[lib]
name = "z80"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]

[profile.test]
opt-level = 3
